baseURL = 'https://callumbicknell.github.io/'
theme = "risotto"
title = "Callum's Blog"
author = "Callum Bicknell"
copyright = "© 2022 Callum Bicknell"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
publishDir = "docs"

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Callum Bicknell"
description = "A wannabe malware developer"
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/CallumBicknell"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:example@example.com"

[[params.socialLinks]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/CallumBicknell5"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
